#!/usr/bin/env bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac ystem and be up and running very
# quickly.

# ---------------------- local utility functions ---------------------

_have() { type "$1" &>/dev/null; }

# create directories
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/bash
mkdir -p "$XDG_CONFIG_HOME"/alacritty
mkdir -p "$XDG_CONFIG_HOME"/alacritty/themes
mkdir -p "$XDG_CONFIG_HOME"/k9s

# check if the directory is empty
if [ ! "$(ls -A "$XDG_CONFIG_HOME/alacritty/themes")" ]; then
	git clone https://github.com/alacritty/alacritty-theme "$XDG_CONFIG_HOME"/alacritty/themes
fi

# Symbolic links
ln -sf "$PWD/alacritty.toml" "$XDG_CONFIG_HOME"/alacritty/alacritty.toml
ln -sf "$PWD/k9s/skin.yml" "$XDG_CONFIG_HOME"/k9s/skin.yml
ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
# ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim

# Install some programs
#_have starship || curl -sS https://starship.rs/install.sh | sh
_have brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
# _have alacritty || brew install --cask alacritty
# _have gh || brew install gh
_have nvim || brew install nvim
_have git || brew install git
_have lazygit || brew install lazygit
_have bat || brew install bat
_have lsd || brew install lsd
_have fzf || brew install fzf
_have k9s || brew install k9s
_have tmux || brew install tmux
_have code || brew install --cask visual-studio-code
_have obs || brew install --cask obs
_have kubecolor || brew install kubecolor/tap/kubecolor

# _have dive || brew install dive
_have dotnet || brew install dotnet
_have earthly || brew install earthly
_have helm || brew install helm
# _have hugo || brew install hugo # static site generator written in Go
# _have jq || brew install jq
_have kind || brew install kind
_have kubectl || brew install kubernetes-cli
_have psql || brew install libpq
# _have node || brew install node
_have tree || brew install tree

brew install --cask amethyst
brew install --cask flameshot
#brew install --cask multipass

brew tap homebrew/cask-fonts
brew install --cask font-fira-code-nerd-font
brew install font-monaspace
