#!/usr/bin/env bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac ystem and be up and running very 
# quickly.

# create directories
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/bash
mkdir -p "$XDG_CONFIG_HOME"/k9s

# Symbolic links
ln -sf "$PWD/k9s/skin.yml" "$XDG_CONFIG_HOME"/k9s/skin.yml
ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
# ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim

curl -sS https://starship.rs/install.sh | sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install --cask iterm2
brew install --cask amethyst

brew install gh neovim lazygit bat lsd fzf k9s coreutils

brew tap homebrew/cask-fonts
brew install --cask font-fira-code-nerd-font
brew install font-monaspace

